// <!-- JavaScript Translations Object -->
var translations = {
	"sent"	  		   : "Sent!",
	"enterYourQuery" 	   : "Enter your query",
	"loading"		   : "Loading...",
	"closeEsc"		   : "Close (Esc)",
	"previousLeftArrowKey"	   : "Previous (Left arrow key)",
	"NextRightArrowKey"	   : "Next (Right arrow key)",
	"of"		   	   : "of",
	"more"		   	   : "MORE",
	"cart"		   	   :"Cart",
	"SearchResult"		   : "Search Result",
	"ChooseTheAmountDonate"    : "Choose the amount you want to donate",
	"blogReviewMessage"	   : "Thank you! Your comment will be published after being approved by the admin.",
	"productReviewMessage"	   : "Thank you! Your review will be published after being approved by the administrator.",
	"ConfirmMailingSubscrive"  : "Please Confirm Your Email Address to Complete Your Subscription",
	"subscribeTellAboutYou"  : "Please tell us about yourself",
	"imageCouldNotLoaded"      : "<a href=\"%url%\">The image<\/a> could not be loaded.",
	"searchInputValidation"    : "Please enter a valid search query.",
	"jqueryValidMsgRequire"    : "This field is required.",
	"jqueryValidMsgRemote"     : "Please fix this field.",
	"jqueryValidMsgEmail"      : "Please enter a valid email address.",
	"jqueryValidMsgUrl"        : "Please enter a valid URL.",
	"jqueryValidMsgDate"       : "Please enter a valid date.",
	"jqueryValidMsgDateISO"    : "Please enter a valid date (ISO).",
	"jqueryValidMsgNumber"     : "Please enter a valid number.",
	"jqueryValidMsgDigits"     : "Please enter only digits.",
	"jqueryValidMsgCreditcard" : "Please enter a valid credit card number.",
	"jqueryValidMsgEqualTo"    : "Please enter the same value again.",
	"jqueryValidMsgAccept"     : "Please enter a value with a valid extension.",
	"jqueryValidMsgMaxlength"  : "Please enter no more than {0} characters.",
	"jqueryValidMsgMinlength"  : "Please enter at least {0} characters.",
	"jqueryValidMsgRangelength":"Please enter a value between {0} and {1} characters long.",
	"jqueryValidMsgRange"	   : "Please enter a value between {0} and {1}.",
	"jqueryValidMsgMax"	   : "Please enter a value less than or equal to {0}.",
	"jqueryValidMsgMin"	   : "Please enter a value greater than or equal to {0}.",
	"sending"		   : "Sending",
	"firstName"		   : "First Name",
	"lastName"		   : "Last Name",
	"phone"			   : "Phone",
	"emailAddress"		   : "Email address",
	"fileUpload"		   : "File Upload",
	"send"			   : "Send",
	"search"		   : "Search",
	"productvalidatorPopover"  : "Required field",
	"SpecialRequest" 	   : "Special Request",
	"restaurantReservation"    : "Restaurant Reservation",
	"ThankYouAuto"		   : "Order completed, thank you for your order!",
	"ThankYouManual"	   : "Order is not completed yet, we will contact you soon",
	"Ok"			   : "OK",
	"OrderNumber"		   : "Order Number",
	"Date"			   : "Date",
	"Hour"			   : "Hour",
	"TableSize"		   : "Table Size",
	"NoAvailableTime"	   : "Sorry, there is no available time for this date, please try another date.",
	"message"	           : "Message",
	"ThankYou"	           : "Thank you",
	"error_title"	   	   : "Error",
	"error_body"	   	   : "Oops something went wrong",
	"limitTickets"	   : "Limit of:",
	"tickets"	   : "Tickets",
	"registrationClosed"       : "Registration is closed. Please contact us for more information.",
	"Sunday"		   : "Sunday",
	"Monday"		   : "Monday",
	"Tuesday"		   : "Tuesday",
	"Wednesday"		   : "Wednesday",
	"Thursday"		   : "Thursday",
	"Friday"		   : "Friday",
	"Saturday"		   : "Saturday",
	"foodDeliverybootBoxTitle" : "Order Window",
	"addToCart"                : "Add To Cart",
	"save"                	   : "Save",       
	"ThankYouAfterSubmmit" 	   : "Thank you for contacting us. We have received your message and will respond to you soon.",    
	"country" 					: "Country",
	"productQuntityLimit" 		: "The product is limited to a maximum of {{units_limitation}} units.",
	"productQuntityLimitMin" 		: "The product is limited to a minimum of {{units_limitation}} units.",
	"forumDeleteTopic" 		: "Deleting a topic will also permanently remove all related replies. Are you sure you want to delete it?",
	"forumDeleteTopicTitle" 	: "Delete Topic",
	"forumDeleteReply" 		: "Are you sure you want to delete this reply?",
	"forumDeleteReplyTitle" 	: "Delete Reply",
	"forumNewTopic" 	: "New Topic",
	"forumCreateNewTopic" 	: "Create a new topic",
	"forumCountOfTotalPosts" 	: "Post a total of {{numbers_of_posts}} posts",
	"forumSearchPlaceholder" 	: "search topics, posts, or categories",
	"forumLastReply" 	: "Last Reply",
	"follow" 	: "Follow",
	"following" 	: "Following",
	"forumReplies" 	: "Replies",
	"forumFrequentPosters" 	: "Frequent Posters",
	"chooseCategory" 	: "Choose Category",
	"linkCopiedToClipboard" 	: "Link copied to clipboard",
	"edit" 	: "Edit",
	"settings" 	: "Settings",
	"created" 	: "Created",
	"seeMore" 	: "See More",
	"options" 	: "Options",
	"joined" 	: "Joined",
	"posted" 	: "Posted",
	"category" 	: "Category",
	"areYouSure": "Are you sure?",
	"yes" 	: "Yes",
	"no" 	: "No",
	"insertTopicTitle" 	: "Insert Topic Title",
	"insertTopicMessage" 	: "Insert Message Topic",
	"reply" 	: "Reply",
	"addReply" 	: "Add reply",
	"address" 	: "Address:",
	"city" 	: "City:",
	"state" 	: "State:",
	"zipCode" 	: "Zip\/Postal Code:",
	"instructions" 	: "Instructions:",
	"country_v2" : "Country:",
	"chooseDate": "Choose Date",
	"chooseDateAndTime": "Choose Date & Time",
	"chooseTime": "Choose Time",
	"total" : "Total:",
	"reviewBad": "bad",
	"reviewPoor": "poor",
	"reviewRegular": "regular",
	"reviewGood": "good",
	"reviewGorgeous": "gorgeous",
	"popupButtonSelected": "Select",
	"eCommerceSort": {
		"sortBy": "Sort By",
		"recommended": "Recommended",
		"byHighPrice": "Price, high to low",
		"byLowerPriceBy": "Price, low to high",
	},
	"globalContactEmail": {
		"fullName": "Full Name",
		"description": "Description",
		"subject": "Subject",
		"contactUs": "Contact Us",
		"infoBox": "Fill out the form or send a direct email to: {{email_address}}",
		"thankYouMessage": "Thank you for contacting us.",
		"thankYouCloseBtn": "Close"		},
	"editStructure": "Edit Structure",
	"editLogo": "Edit",
	"eventNumberOfTickets": "Choose how many tickets you would like to purchase.",
	"magicBtn": {
		"editMagicContactButton": "Edit Contact", 
		"editMagicShareButton": "Edit Share", 
		"contactUs": {
			"title": "Contact",
			"submitBtn": "Contact Us",
			"ThankYouAfterSubmmit": "Thank you for contacting us. We have received your message and will respond to you soon.",
			"fields": {
				"name": "Name",
				"phone": "Phone",
				"emailAddress": "Email address",
				"emailAddressValidationdMsg": "Please enter a valid email.",
				"message": "Message",
				"requiredMsg": "This field is required.",
			}
		},
		"copyLink": {
			"success": "The link has been copied to the clipboard.",
		},
		"ExternalLinksPreventor": {
			"title": "Published Version Only",
			"previewExternalLinkMsg": "You are trying to exit to an external link from your website's preview mode. Please publish your website and try again from the URL of your website.",
		},
		"facebookMessenger": {
			"title": "Facebook",
		},
		"whatsApp": {
			"title": "WhatsApp",
		},
		"phone": {
			"title": "Phone",
		},
		"skype": {
			"title": "Skype",
		},
		"telegram": {
			"title": "Telegram",
		},
		"facebook": {
			"title": "Facebook",
		},
		"twitter": {
			"title": "Twitter",
		},
		"pinterest": {
			"title": "Pinterest",
		},
		"gmail": {
			"title": "Gmail",
		},
		"linkedIn": {
			"title": "LinkedIn",
		},
		"tumblr": {
			"title": "Tumblr",
		},
		"emailApp": {
			"title": "Email App",
		},
		"copyLink": {
			"title": "Copy Link",
		}
	},
	"fillOutAtLeastOneField": "You need to fill out at least one field before you submit this form.",
	"productCallToAction": {
		"fullName": "Full Name",
		"description": "Description",
		"subject": "Subject",
		"title": "Contact Us",
		"infoBox": "Please fill out the following form if you are interested in this product:",
		"thankYouMessage": "Thank you for contacting us.",
		"thankYouCloseBtn": "Close",
		"phone": "Phone",
		"productName": "Product Name:"		},
	"flipClock": {
		"years"   : "Years",
		"months"  : "Months",
		"days"    : "Days",
		"hours"   : "Hours",
		"minutes" : "Minutes",
		"seconds" : "Seconds"		},
	"previewExternalLinkTitle": "External link",
	"previewExternalLinkMsg": "You are trying to exit to an external link {{externalLink}} from the control panel, which is disabled here. Please go to full screen preview to get it working.",
	"returnPolicy": "Return Policy",
	"calendarHandler": {
		"days": {
			"sunday": "Sunday",
			"monday": "Monday", 
			"tuesday": "Tuesday", 
			"wednesday": "Wednesday", 
			"thursday": "Thursday", 
			"friday": "Friday", 
			"saturday": "Saturday"			},
		"daysShort": {
			"sun": "Sun", 
			"mon": "Mon", 
			"tue": "Tue", 
			"wed": "Wed", 
			"thu": "Thu", 
			"fri": "Fri", 
			"sat": "Sat"			},
		"daysMin": {
			"su": "Sun", 
			"mo": "Mon", 
			"tu": "Tue", 
			"we": "Wed", 
			"th": "Thu", 
			"fr": "Fri", 
			"sa": "Sat"			},
		"months": {
			"january": "January", 
			"february": "February",
			"march": "March", 
			"april": "April", 
			"may": "May", 
			"june": "June", 
			"july": "July", 
			"august": "August", 
			"september": "September", 
			"october": "October", 
			"november": "November", 
			"december": "December"			},
		"monthsShort": {
			"jan": "Jan", 
			"feb": "Feb", 
			"mar": "Mar", 
			"apr": "Apr", 
			"may": "May", 
			"jun": "Jun", 
			"jul": "Jul", 
			"aug": "Aug", 
			"sep": "Sep", 
			"oct": "Oct", 
			"nov": "Nov", 
			"dec": "Dec"			},
		"today": "Today",
	},
			"layouts": "Layouts",
	"pages": "Pages",
	"remove": "Remove"	};